# Generated by Django 4.2.13 on 2026-06-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0004_prompt_agent_pattern_prompt_prompt_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('model_name', models.CharField(default='jhgan/ko-sroberta-multitask', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='prompts.prompt')),
            ],
            options={
                'verbose_name': '프롬프트 임베딩',
                'verbose_name_plural': '프롬프트 임베딩 목록',
            },
        ),
        migrations.CreateModel(
            name='AgentTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decomposed_steps', models.JSONField(default=list)),
                ('suggested_tools', models.JSONField(default=list)),
                ('system_messages', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('model_used', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='prompts.prompt')),
            ],
            options={
                'verbose_name': '에이전트 변환 결과',
                'verbose_name_plural': '에이전트 변환 결과 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prompt', '-created_at'], name='ai_gateway__prompt__f3b2cd_idx')],
            },
        ),
    ]
