# Generated by Django 4.2.13 on 2026-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttransformation',
            name='context_strategy_summary',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='agenttransformation',
            name='harness_strategy_summary',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='agenttransformation',
            name='overall_pattern',
            field=models.CharField(choices=[('Sequential', 'Sequential'), ('ReAct', 'ReAct'), ('Reflection', 'Reflection'), ('MultiAgent', 'Multi-agent')], default='Sequential', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agenttransformation',
            index=models.Index(fields=['overall_pattern'], name='ai_gateway__overall_9c4a6b_idx'),
        ),
    ]
