# Generated by Django 4.2.13 on 2026-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0002_agent_transformation_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttransformation',
            name='quality_strategy_summary',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='검증 전략 요약'),
        ),
    ]
