# Generated by Django 4.2.13 on 2026-06-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0004_blueprint_design'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blueprintdesign',
            new_name='ai_gateway__user_id_1c7d15_idx',
            old_name='ai_gateway__user_id_6e0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='blueprintdesign',
            new_name='ai_gateway__status_9e85a5_idx',
            old_name='ai_gateway__status_8a2c1e_idx',
        ),
    ]
