global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: django
    static_configs:
      - targets: ['web:8000']
    metrics_path: /metrics

  - job_name: fastapi
    static_configs:
      - targets: ['ai_server:8000']
    metrics_path: /metrics
