# Generated by Django 6.0.4 on 2026-05-04 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='프롬프트 본문')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('ai_model', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4', 'GPT-4'), ('claude-3-5-sonnet', 'Claude 3.5 Sonnet'), ('claude-3-opus', 'Claude 3 Opus'), ('gemini-1-5-pro', 'Gemini 1.5 Pro'), ('gemini-2-0-flash', 'Gemini 2.0 Flash'), ('other', '기타')], default='other', max_length=30, verbose_name='AI 모델')),
                ('is_free', models.BooleanField(default=True, verbose_name='무료 여부')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='가격')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.category', verbose_name='카테고리')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_prompts', to=settings.AUTH_USER_MODEL, verbose_name='삭제한 사용자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('tags', models.ManyToManyField(blank=True, related_name='prompts', to='prompts.tag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '프롬프트',
                'verbose_name_plural': '프롬프트 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prompts/%Y/%m/%d/', verbose_name='파일')),
                ('file_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_type', models.CharField(max_length=50, verbose_name='파일 타입')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기(bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='prompts.prompt', verbose_name='프롬프트')),
            ],
            options={
                'verbose_name': '프롬프트 파일',
                'verbose_name_plural': '프롬프트 파일 목록',
            },
        ),
    ]
