# Generated by Django 4.2.13 on 2026-06-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_update_ai_model_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='agent_pattern',
            field=models.CharField(blank=True, choices=[('', '해당 없음'), ('sequential', 'Sequential'), ('react', 'ReAct'), ('reflection', 'Reflection'), ('multi_agent', 'Multi-agent')], default='', max_length=20, verbose_name='에이전트 패턴'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(choices=[('single_prompt', '단일 프롬프트'), ('agent_recipe', '에이전트 레시피'), ('mcp_package', 'MCP 패키지')], default='single_prompt', max_length=20, verbose_name='프롬프트 유형'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='workflow_steps',
            field=models.JSONField(blank=True, default=list, verbose_name='워크플로우 단계'),
        ),
    ]
