# Generated by Django 4.2.13 on 2026-06-09 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_prompt_agent_pattern_prompt_prompt_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='레시피 카테고리명')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '레시피 카테고리',
                'verbose_name_plural': '레시피 카테고리 목록',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='recipe_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.recipecategory', verbose_name='레시피 카테고리'),
        ),
    ]
