# Generated by Django 4.2.13 on 2026-06-01 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0004_prompt_agent_pattern_prompt_prompt_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('transform', '에이전트 변환'), ('embed', '임베딩')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('PROCESSING', '처리 중'), ('SUCCESS', '성공'), ('FAIL', '실패')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tasks_task_user_id_d01da7_idx'), models.Index(fields=['prompt', 'task_type'], name='tasks_task_prompt__1ea281_idx'), models.Index(fields=['status', '-created_at'], name='tasks_task_status_a96e51_idx')],
            },
        ),
    ]
